Optimize Pandoc installation: Check if already installed before proceeding with installation

diff --git a/.github/workflows/update_tree.yml b/.github/workflows/update_tree.yml
--- a/.github/workflows/update_tree.yml
+++ b/.github/workflows/update_tree.yml
@@ -25,8 +25,13 @@ jobs:
 
     - name: Install Pandoc
       run:
-        apt-get update && apt-get install -y pandoc
-
+        if ! command -v pandoc &> /dev/null; then
+          echo "Pandoc not found. Installing..."
+          sudo apt-get update
+          sudo apt-get install -y pandoc
+        else
+        echo "Pandoc is already installed. Skipping installation."
+        fi
     # Step 4: Convert Markdown to HTML
     - name: Convert Markdown to HTML
       run: |
